name: Build Cross-Platform Packages

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y fakeroot

    - name: Build with Maven
      run: mvn -B install

    # --- CHANGE: Simplified module-path to point to the directory ---
    - name: Run jpackage for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        jpackage --type app-image \
          --app-version 1.0.0 \
          --dest target/dist \
          --name "Screen Locker" \
          --module-path "target/dependencies:target/screenlockerdesktop-1.0-SNAPSHOT.jar" \
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec \
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp \
          --icon package/linux/icon.png

    # --- CHANGE: Simplified module-path to point to the directory ---
    - name: Run jpackage for Windows
      if: matrix.os == 'windows-latest'
      run: |
        jpackage --type app-image `
          --app-version 1.0.0 `
          --dest target/dist `
          --name "Screen Locker" `
          --module-path "target/dependencies;target/screenlockerdesktop-1.0-SNAPSHOT.jar" `
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec `
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp `
          --icon package/windows/icon.ico

    # --- CHANGE: Simplified module-path to point to the directory ---
    - name: Run jpackage for macOS
      if: matrix.os == 'macos-latest'
      run: |
        jpackage --type dmg \
          --app-version 1.0.0 \
          --dest target/dist \
          --name "Screen Locker" \
          --module-path "target/dependencies:target/screenlockerdesktop-1.0-SNAPSHOT.jar" \
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec \
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp \
          --icon package/macos/icon.icns

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.os }}
        path: target/dist/*
