name: Build and Release Cross-Platform Packages

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y fakeroot

    - name: Build with Maven
      run: mvn -B install

    # --- JPackage for Linux ---
    - name: Run jpackage for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        jpackage --type app-image \
          --app-version 1.0.0 \
          --dest target/dist \
          --name "ScreenLocker" \
          --module-path "target/dependencies:target/screenlockerdesktop-1.0-SNAPSHOT.jar" \
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec \
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp \
          --icon package/linux/icon.png
    
    - name: Archive Linux app-image
      if: matrix.os == 'ubuntu-latest'
      # CHANGED: Updated the directory name to match the new jpackage name
      run: tar -czf target/dist/Screen-Locker-Linux-x64.tar.gz -C target/dist "ScreenLocker"

    # --- JPackage for Windows ---
    - name: Run jpackage for Windows
      if: matrix.os == 'windows-latest'
      run: |
        jpackage --type app-image `
          --app-version 1.0.0 `
          --dest target/dist `
          --name "ScreenLocker" `
          --module-path "target/dependencies;target/screenlockerdesktop-1.0-SNAPSHOT.jar" `
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec `
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp `
          --icon package/windows/icon.ico

    - name: Archive Windows app-image
      if: matrix.os == 'windows-latest'
      # CHANGED: Updated the directory path to match the new jpackage name
      run: Compress-Archive -Path target/dist/ScreenLocker -DestinationPath target/dist/Screen-Locker-Windows-x64.zip
      
    # --- JPackage for macOS ---
    - name: Run jpackage for macOS
      if: matrix.os == 'macos-latest'
      run: |
        jpackage --type dmg \
          --app-version 1.0.0 \
          --dest target/dist \
          --name "ScreenLocker" \
          --module-path "target/dependencies:target/screenlockerdesktop-1.0-SNAPSHOT.jar" \
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec \
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp 
          --icon package/macos/icon.icns

    - name: Upload Linux Artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.os }}
        path: target/dist/*.tar.gz

    - name: Upload Windows Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.os }}
        path: target/dist/*.zip

    - name: Upload macOS Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.os }}
        path: target/dist/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Development Build"
          body: "This is the latest build from the main branch."
          prerelease: false
          files: |
            artifacts/package-ubuntu-latest/*
            artifacts/package-windows-latest/*
            artifacts/package-macos-latest/*
