name: Build and Release Cross-Platform Packages

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*.*.*' # Trigger workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y fakeroot

    - name: Build with Maven
      run: mvn -B install

    # --- JPackage for Linux ---
    - name: Run jpackage for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        jpackage --type app-image \
          --app-version 1.0.0 \
          --dest target/dist \
          --name "ScreenLocker" \
          --module-path "target/dependencies:target/screenlockerdesktop-1.0-SNAPSHOT.jar" \
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec \
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp \
          --icon package/linux/icon.png
    
    - name: Archive Linux app-image
      if: matrix.os == 'ubuntu-latest'
      run: tar -czf target/dist/Screen-Locker-Linux-x64.tar.gz -C target/dist "ScreenLocker"

    # --- JPackage for Windows ---
    - name: Run jpackage for Windows
      if: matrix.os == 'windows-latest'
      run: |
        jpackage --type app-image `
          --app-version 1.0.0 `
          --dest target/dist `
          --name "ScreenLocker" `
          --module-path "target/dependencies;target/screenlockerdesktop-1.0-SNAPSHOT.jar" `
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec `
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp `
          --icon package/windows/icon.ico

    - name: Archive Windows app-image
      if: matrix.os == 'windows-latest'
      run: Compress-Archive -Path target/dist/ScreenLocker -DestinationPath target/dist/Screen-Locker-Windows-x64.zip
      
    # --- JPackage for macOS ---
    - name: Run jpackage for macOS
      if: matrix.os == 'macos-latest'
      run: |
        jpackage --type dmg \
          --app-version 1.0.0 \
          --dest target/dist \
          --name "ScreenLocker" \
          --module-path "target/dependencies:target/screenlockerdesktop-1.0-SNAPSHOT.jar" \
          --add-modules de.hypno.screenlockerdesktop,javafx.controls,javafx.fxml,org.java_websocket,jdk.crypto.ec \
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp \
          --icon package/macos/icon.icns

    - name: Upload Linux Artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: package-linux
        path: target/dist/*.tar.gz

    - name: Upload Windows Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: package-windows
        path: target/dist/*.zip

    - name: Upload macOS Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: package-macos
        path: target/dist/*.dmg

  # --- New Release Job ---
  release:
    name: Create Release
    runs-on: ubuntu-latest
    # The release job depends on the build job and will only run if all matrix builds succeed
    needs: build
    # The release job needs permissions to write to the repository's releases
    permissions:
      contents: write
      
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          # The directory where all artifacts will be downloaded
          path: artifacts

      - name: Create GitHub Release
        # Using softprops/action-gh-release action to create the release and upload assets
        # Use v1 to doge a bug
        uses: softprops/action-gh-release@v1
        with:
          # The files to upload as assets to the release
          files: |
            artifacts/package-linux/*.tar.gz
            artifacts/package-windows/*.zip
            artifacts/package-macos/*.dmg
          # Automatically generate release notes from commits
          generate_release_notes: true
