name: Build Cross-Platform Packages

on:
  push:
    branches: [ "main", "master" ] # Triggers the build on a push to main/master

jobs:
  build:
    # Run on both Ubuntu and Windows virtual machines
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # For the Windows build, install WiX Toolset using Chocolatey
    - name: Install WiX Toolset (Windows only)
      if: matrix.os == 'windows-latest'
      run: choco install wixtoolset -y --version 3.14.0

    # For the Linux build, install the necessary packaging dependencies
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y fakeroot

    - name: Build with Maven and JLink
      run: mvn -B install javafx:jlink

    - name: Run jpackage for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        jpackage --type app-image \
          --app-version 1.0.0 \
          --dest target/dist \
          --name "Screen Locker" \
          --runtime-image target/screenlocker-runtime \
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp \
          --icon package/linux/icon.png

    - name: Run jpackage for Windows
      if: matrix.os == 'windows-latest'
      run: |
        jpackage --type app-image `
          --app-version 1.0.0 `
          --dest target/dist `
          --name "Screen Locker" `
          --runtime-image target/screenlocker-runtime `
          --module de.hypno.screenlockerdesktop/de.hypno.screenlockerdesktop.MainApp `
          --icon package/windows/icon.ico

    # Upload the packaged application. This uses the updated v4 action.
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.os }}
        path: target/dist/*